name: Validate, build, and test on every push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Run prettier
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: format
      - name: Check linter
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
      - name: Build the project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
